# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.link import Link
from openapi_server import util


class CollectionDataQueriesPosition(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, link: Link=None):
        """CollectionDataQueriesPosition - a model defined in OpenAPI

        :param link: The link of this CollectionDataQueriesPosition.
        """
        self.openapi_types = {
            'link': Link
        }

        self.attribute_map = {
            'link': 'link'
        }

        self._link = link

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CollectionDataQueriesPosition':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The collection_data_queries_position of this CollectionDataQueriesPosition.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self):
        """Gets the link of this CollectionDataQueriesPosition.


        :return: The link of this CollectionDataQueriesPosition.
        :rtype: Link
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this CollectionDataQueriesPosition.


        :param link: The link of this CollectionDataQueriesPosition.
        :type link: Link
        """

        self._link = link
