# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.domain_description import DomainDescription
from openapi_server.models.one_ofnumberstring import OneOfnumberstring
from openapi_server.models.one_ofobjectobject import OneOfobjectobject
from openapi_server.models.parameter import Parameter
from openapi_server import util


class CoverageJSON(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type: object = None, domain: DomainDescription = None, domain_type: object = None, parameters: Dict[str, Parameter] = None, referencing: Dict[str, OneOfobjectobject] = None, ranges: Dict[str, OneOfobjectobject] = None, coverages: Dict[str, OneOfobjectobject] = None):
        """CoverageJSON - a model defined in OpenAPI

        :param type: The type of this CoverageJSON.
        :param domain: The domain of this CoverageJSON.
        :param parameters: The parameters of this CoverageJSON.
        :param ranges: The ranges of this CoverageJSON.
        """
        self.openapi_types = {
            'type': object,
            'domain_type': object,
            'domain': DomainDescription,
            'parameters': Dict[str, Parameter],
            'ranges': Dict[str, OneOfobjectobject],
            'referencing': Dict[str, OneOfobjectobject],
            'coverages': Dict[str, OneOfobjectobject]
        }

        self.attribute_map = {
            'type': 'type',
            'domain_type': 'domainType',
            'domain': 'domain',
            'parameters': 'parameters',
            'referencing': 'referencing',
            'ranges': 'ranges',
            'coverages': 'coverages'
        }

        self._type = type
        self._domain = domain
        self._parameters = parameters
        self._referencing = referencing
        self._ranges = ranges
        self._coverages = coverages
        self._domain_type = domain_type

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CoverageJSON':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The coverageJSON of this CoverageJSON.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_type(self):
        """Gets the domain_type of this DomainDescription.

        Domain type

        :return: The domain_type of this DomainDescription.
        :rtype: object
        """
        return self._domain_type

    @domain_type.setter
    def domain_type(self, domain_type):
        """Sets the domain_type of this DomainDescription.

        Domain type

        :param domain_type: The domain_type of this DomainDescription.
        :type domain_type: object
        """
        allowed_values = [Grid, Point, Trajectory, PointSeries, PolygonSeries, MultiPolygon, MultiPoint, VerticalProfile]  # noqa: E501
        if domain_type not in allowed_values:
            raise ValueError(
                "Invalid value for `domain_type` ({0}), must be one of {1}"
                .format(domain_type, allowed_values)
            )

        self._domain_type = domain_type

    @property
    def type(self):
        """Gets the type of this CoverageJSON.

        Coverage domain type

        :return: The type of this CoverageJSON.
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CoverageJSON.

        Coverage domain type

        :param type: The type of this CoverageJSON.
        :type type: object
        """
        allowed_values = ["Coverage", "CoverageCollection", "Domain"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def domain(self):
        """Gets the domain of this CoverageJSON.


        :return: The domain of this CoverageJSON.
        :rtype: DomainDescription
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this CoverageJSON.


        :param domain: The domain of this CoverageJSON.
        :type domain: DomainDescription
        """
        if domain is None:
            raise ValueError("Invalid value for `domain`, must not be `None`")

        self._domain = domain

    @property
    def parameters(self):
        """Gets the parameters of this CoverageJSON.


        :return: The parameters of this CoverageJSON.
        :rtype: Dict[str, Parameter]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this CoverageJSON.


        :param parameters: The parameters of this CoverageJSON.
        :type parameters: Dict[str, Parameter]
        """
        if parameters is None:
            raise ValueError(
                "Invalid value for `parameters`, must not be `None`")

        self._parameters = parameters

    @property
    def ranges(self):
        """Gets the ranges of this CoverageJSON.


        :return: The ranges of this CoverageJSON.
        :rtype: Dict[str, OneOfobjectobject]
        """
        return self._ranges

    @ranges.setter
    def ranges(self, ranges):
        """Sets the ranges of this CoverageJSON.


        :param ranges: The ranges of this CoverageJSON.
        :type ranges: Dict[str, OneOfobjectobject]
        """
        if ranges is None:
            raise ValueError("Invalid value for `ranges`, must not be `None`")

        self._ranges = ranges

    @property
    def coverages(self):
        """Gets the coverages of this CoverageJSON.


        :return: The coverages of this CoverageJSON.
        :rtype: Dict[str, OneOfobjectobject]
        """
        return self._coverages

    @coverages.setter
    def coverages(self, coverages):
        """Sets the coverages of this CoverageJSON.


        :param coverages: The coverages of this CoverageJSON.
        :type coverages: Dict[str, OneOfobjectobject]
        """
        if coverages is None:
            raise ValueError(
                "Invalid value for `coverages`, must not be `None`")

        self._coverages = coverages

    @property
    def referencing(self):
        """Gets the referencing of this CoverageJSON.


        :return: The referencing of this CoverageJSON.
        :rtype: Dict[str, OneOfobjectobject]
        """
        return self._referencing

    @referencing.setter
    def referencing(self, referencing):
        """Sets the referencing of this CoverageJSON.


        :param referencing: The referencing of this CoverageJSON.
        :type referencing: Dict[str, OneOfobjectobject]
        """
        if referencing is None:
            raise ValueError(
                "Invalid value for `referencing`, must not be `None`")

        self._referencing = referencing
