# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CrsObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, crs: str=None, wkt: str=None):
        """CrsObject - a model defined in OpenAPI

        :param crs: The crs of this CrsObject.
        :param wkt: The wkt of this CrsObject.
        """
        self.openapi_types = {
            'crs': str,
            'wkt': str
        }

        self.attribute_map = {
            'crs': 'crs',
            'wkt': 'wkt'
        }

        self._crs = crs
        self._wkt = wkt

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CrsObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The crsObject of this CrsObject.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def crs(self):
        """Gets the crs of this CrsObject.

        name of the coordinate reference system, used as the value in the crs query parameter to define the required output CRS

        :return: The crs of this CrsObject.
        :rtype: str
        """
        return self._crs

    @crs.setter
    def crs(self, crs):
        """Sets the crs of this CrsObject.

        name of the coordinate reference system, used as the value in the crs query parameter to define the required output CRS

        :param crs: The crs of this CrsObject.
        :type crs: str
        """
        if crs is None:
            raise ValueError("Invalid value for `crs`, must not be `None`")

        self._crs = crs

    @property
    def wkt(self):
        """Gets the wkt of this CrsObject.

        Well Known text description of the coordinate reference system

        :return: The wkt of this CrsObject.
        :rtype: str
        """
        return self._wkt

    @wkt.setter
    def wkt(self, wkt):
        """Sets the wkt of this CrsObject.

        Well Known text description of the coordinate reference system

        :param wkt: The wkt of this CrsObject.
        :type wkt: str
        """
        if wkt is None:
            raise ValueError("Invalid value for `wkt`, must not be `None`")

        self._wkt = wkt
