# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DataQueryCoords(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, type: str=None, example: str=None):
        """DataQueryCoords - a model defined in OpenAPI

        :param description: The description of this DataQueryCoords.
        :param type: The type of this DataQueryCoords.
        :param example: The example of this DataQueryCoords.
        """
        self.openapi_types = {
            'description': str,
            'type': str,
            'example': str
        }

        self.attribute_map = {
            'description': 'description',
            'type': 'type',
            'example': 'example'
        }

        self._description = description
        self._type = type
        self._example = example

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DataQueryCoords':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The dataQuery_coords of this DataQueryCoords.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self):
        """Gets the description of this DataQueryCoords.


        :return: The description of this DataQueryCoords.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DataQueryCoords.


        :param description: The description of this DataQueryCoords.
        :type description: str
        """

        self._description = description

    @property
    def type(self):
        """Gets the type of this DataQueryCoords.


        :return: The type of this DataQueryCoords.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DataQueryCoords.


        :param type: The type of this DataQueryCoords.
        :type type: str
        """

        self._type = type

    @property
    def example(self):
        """Gets the example of this DataQueryCoords.


        :return: The example of this DataQueryCoords.
        :rtype: str
        """
        return self._example

    @example.setter
    def example(self, example):
        """Sets the example of this DataQueryCoords.


        :param example: The example of this DataQueryCoords.
        :type example: str
        """

        self._example = example
