# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.link import Link
from openapi_server import util


class Groups(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, links: List[Link]=None, members: List[Link]=None):
        """Groups - a model defined in OpenAPI

        :param links: The links of this Groups.
        :param members: The members of this Groups.
        """
        self.openapi_types = {
            'links': List[Link],
            'members': List[Link]
        }

        self.attribute_map = {
            'links': 'links',
            'members': 'members'
        }

        self._links = links
        self._members = members

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Groups':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The groups of this Groups.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self):
        """Gets the links of this Groups.


        :return: The links of this Groups.
        :rtype: List[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Groups.


        :param links: The links of this Groups.
        :type links: List[Link]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")

        self._links = links

    @property
    def members(self):
        """Gets the members of this Groups.


        :return: The members of this Groups.
        :rtype: List[Link]
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this Groups.


        :param members: The members of this Groups.
        :type members: List[Link]
        """
        if members is None:
            raise ValueError("Invalid value for `members`, must not be `None`")

        self._members = members
