# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ObservedPropertyCategories(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, label: str=None, description: str=None):
        """ObservedPropertyCategories - a model defined in OpenAPI

        :param id: The id of this ObservedPropertyCategories.
        :param label: The label of this ObservedPropertyCategories.
        :param description: The description of this ObservedPropertyCategories.
        """
        self.openapi_types = {
            'id': str,
            'label': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'description': 'description'
        }

        self._id = id
        self._label = label
        self._description = description

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ObservedPropertyCategories':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The observedProperty_categories of this ObservedPropertyCategories.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ObservedPropertyCategories.

        URI linking to an external registry which contains the definitive definition of the observed property

        :return: The id of this ObservedPropertyCategories.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ObservedPropertyCategories.

        URI linking to an external registry which contains the definitive definition of the observed property

        :param id: The id of this ObservedPropertyCategories.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def label(self):
        """Gets the label of this ObservedPropertyCategories.


        :return: The label of this ObservedPropertyCategories.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ObservedPropertyCategories.


        :param label: The label of this ObservedPropertyCategories.
        :type label: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")

        self._label = label

    @property
    def description(self):
        """Gets the description of this ObservedPropertyCategories.


        :return: The description of this ObservedPropertyCategories.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ObservedPropertyCategories.


        :param description: The description of this ObservedPropertyCategories.
        :type description: str
        """

        self._description = description
