# generated by datamodel-codegen:
#   filename:  testapi4.yaml
#   timestamp: 2022-02-10T13:42:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from openapi_server.models.base_model_ import Model


class OneOfnumberstring(Model):
    __root__: Union[float, str]
