# generated by datamodel-codegen:
#   filename:  testapi4.yaml
#   timestamp: 2022-02-10T13:42:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from openapi_server.models.base_model_ import Model

from openapi_server.models.point_geo_json import PointGeoJSON
from openapi_server.models.multipoint_geo_json import MultipointGeoJSON
from openapi_server.models.linestring_geo_json import LinestringGeoJSON
from openapi_server.models.multilinestring_geo_json import MultilinestringGeoJSON
from openapi_server.models.polygon_geo_json import PolygonGeoJSON
from openapi_server.models.multipolygon_geo_json import MultipolygonGeoJSON
# from openapi_server.models.geometrycollection_geo_json import GeometrycollectionGeoJSON


class OneOfpointGeoJSONmultipointGeoJSONlinestringGeoJSONmultilinestringGeoJSONpolygonGeoJSONmultipolygonGeoJSONgeometrycollectionGeoJSON(Model):
    __root__: Union[PointGeoJSON, MultipointGeoJSON, LinestringGeoJSON,
                    MultilinestringGeoJSON, PolygonGeoJSON, MultipolygonGeoJSON]  # , GeometrycollectionGeoJSON]
